src/app/show/urls.py
from django.urls import path, include

from . import views

app_name = "show"

urlpatterns = (
    path("", views.ShowListView.as_view(), name="list"),
    path("<int:pk>", views.ShowDetailView.as_view(), name="detail"),
    path("<int:pk>/watch", views.ShowWatchView.as_view(), name="watch"),
    path("<int:pk>/refresh", views.refresh_show_cache, name="refresh"),
    path("<int:pk>/update", views.update_show, name="update"),
    path("<int:sid>/add/src/nyaa", views.AddNyaaSourceView.as_view(), name="add_src_nyaa"),
)

src/app/watchlist/urls.py
from django.urls import path

from . import views

app_name = "watchlist"

urlpatterns = (
    path("", views.WatchlistListView.as_view(), name="list"),
    path("<int:pk>", views.WatchlistDetailView.as_view(), name="detail"),
    path("<int:pk>/curl", views.WatchlistCurlView.as_view(), name="curl"),
    path("<int:pk>/refresh/all", views.refresh_all, name="refresh_all"),
    path("<int:pk>/refresh/promising", views.refresh_promising, name="refresh_promising"),
    path("<int:pk>/<int:item>/ack", views.ack, name="ack"),
    path("entries/<int:pk>", views.WatchlistEntryDetailView.as_view(), name="entry_detail"),
    path("entries/<int:pk>/edit", views.WatchlistEntryUpdateView.as_view(), name="entry_update"),
    # path("entries/<int:pk>/delete", views.WatchlistEntryDeleteView.as_view(), name="entry_delete"),
    path("import_twcli", views.WatchlistTwcliImportView.as_view(), name="import_twcli"),
    path("import_malinder", views.MalinderImportView.as_view(), name="import_malinder"),
)

src/app/watchlist/models.py
import datetime

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils import timezone

import show.models as show_models


class Watchlist(models.Model):
    # Fields
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)

    name = models.CharField(max_length=255)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    def __repr__(self) -> str:
        return f"{self.__class__}({self.name})"

    def __str__(self) -> str:
        return str(self.name)

    def get_new_watchlinks(self):
        data = []
        for entry in self.get_active_entries():
            for ep in entry.get_new_episodes():
                data.append({'show': ep.source.show, 'episode': ep.episode_counter, 'url': ep.url})
        return data

    def get_active_entries(self):
        filter_active = Q(status=WatchListEntry.WatchStatus.Import) \
                        | Q(status=WatchListEntry.WatchStatus.Plan) \
                        | Q(status=WatchListEntry.WatchStatus.Watch)
        return self.entries.filter(filter_active)

    def get_backlog_entries(self):
        filter_active = Q(status=WatchListEntry.WatchStatus.Backlog)
        return self.entries.filter(filter_active)

    class Meta:
        ordering = ('name',)


class WatchListPermission(models.Model):
    class AccessLevel(models.TextChoices):
        L10_View = 'L10', 'L10_View'
        L20_Refresh = 'L20', 'L20_Refresh'
        L30_Edit = 'L30', 'L30_Mark'
        L40_Edit = 'L40', 'L40_Edit'
        L50_Manage = 'L50', 'L50_Manage'
        L60_Successor = 'L60', 'L60_Successor'

    # Fields
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)

    watchlist = models.ForeignKey(Watchlist,
                                  on_delete=models.CASCADE,
                                  related_name='permission',
                                  related_query_name='permissions')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    access_level = models.CharField(max_length=3, choices=AccessLevel.choices)

    def __repr__(self) -> str:
        return f"{self.__class__}({self.watchlist}, {self.access_level}, {self.user})"

    def __str__(self) -> str:
        return f"{self.watchlist}[{self.access_level}]: {self.user}"

    class Meta:
        ordering = ('access_level', 'user',)


class WatchListEntry(models.Model):
    class WatchStatus(models.TextChoices):
        Undefined = 'U', 'Undefined'
        Backlog = 'B', 'Backlog'
        Plan = 'P', 'PlanToWatch'
        Watch = 'W', 'Watching'
        Complete = 'C', 'Complete'
        Drop = 'D', 'Dropped'
        Import = 'I', 'Imported'

    # Fields
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)

    watchlist = models.ForeignKey(Watchlist,
                                  on_delete=models.CASCADE,
                                  related_name='entries',
                                  related_query_name='entry')
    status = models.CharField(max_length=1, choices=WatchStatus.choices)

    show = models.ForeignKey(show_models.Show, on_delete=models.CASCADE)
    season = models.PositiveIntegerField(default=0)
    episode = models.PositiveIntegerField(default=0)
    revision = models.PositiveIntegerField(default=0)

    def __str__(self) -> str:
        return f'{self.watchlist}[{self.status},S{self.episode_counter}]({self.show})'

    class Meta:
        ordering = ('-status', 'show__name',)

    @property
    def episode_counter(self):
        if self.season == 0:
            out = f'{self.episode}'
        else:
            out = f'{self.season}x{self.episode:02}'

        if self.revision > 1:
            out += f'v{self.revision}'

        return out

    @property
    def cache_refresh_date(self) -> datetime.datetime:
        try:
            qs = self.show.ext_srcs.get().cache_items.all().order_by('-timestamp')[0]
            return qs.timestamp
        except IndexError:
            return None
        except show_models.NyaaSource.MultipleObjectsReturned:
            # if there are multiple sources, use newest of them
            ts = []
            for src in self.show.ext_srcs.all():
                try:
                    ts.append(src.cache_items.all().order_by('-timestamp')[0].timestamp)
                except IndexError:
                    pass  # no items in cache
            if len(ts) == 0:
                # no sources had any cached data
                return None
            return max(ts)

    @property
    def cache_release_date(self) -> datetime.datetime:
        try:
            qs = self.show.ext_srcs.get().cache_items.all().order_by('-season', '-episode', '-revision')[0]
            return qs.pub_date
        except IndexError:
            return None
        except show_models.NyaaSource.MultipleObjectsReturned:
            pd = []
            for src in self.show.ext_srcs.all():
                try:
                    pd.append(src.cache_items.all().order_by('-season', '-episode', '-revision')[0].pub_date)
                except IndexError:
                    pass
            if len(pd) == 0:
                # no sources had any cached data
                return None
            return max(pd)

    @property
    def cache_episode_counter(self):
        try:
            qs = self.show.ext_srcs.get().cache_items.all().order_by('-season', '-episode', '-revision')[0]
            return qs.episode_counter
        except IndexError:
            return ""
        except show_models.NyaaSource.MultipleObjectsReturned:
            ec = []
            for src in self.show.ext_srcs.all():
                try:
                    ec.append(src.cache_items.all().order_by('-season', '-episode', '-revision')[0].episode_counter)
                except IndexError:
                    pass
            return ", ".join(ec)

    def get_new_watchlinks(self):
        data = self.show.get_cachedata(self.season, self.episode, self.revision)
        return [ep.url for ep in data]

    def get_watchlinks(self):
        data = self.show.get_cachedata()
        return [ep.url for ep in data]

    def get_new_episodes(self):
        if self.status == self.WatchStatus.Import:
            return self.show.get_cachedata()
        else:
            return self.show.get_cachedata(self.season, self.episode, self.revision)

    def get_episodes(self):
        return self.show.get_cachedata()

    @property
    def release_age(self) -> int:
        try:
            return (timezone.now() - self.cache_release_date).total_seconds()
        except ValueError:
            return 0
        except TypeError:  # most likely cache_release_date returned 'None'
            return 0

    @property
    def is_release_overdue(self) -> bool:
        return self.release_age > 604800  # 7*24*60*60 = 1w

    @property
    def release_expected_date(self) -> datetime:
        return self.cache_release_date + datetime.timedelta(days=7)

    @property
    def release_progress(self) -> int:
        if self.release_age <= 604800:  # 7*24*60*60 = 1w
            return self.release_age
        else:
            return 604800

    @property
    def release_overdue(self) -> int:
        if self.release_age <= 604800:  # 7*24*60*60 = 1w
            return 0
        else:
            return self.release_age - 604800

    @property
    def release_progress_percent(self) -> int:
        if not self.is_release_overdue:
            return round(self.release_progress / 604800 * 100)
        else:
            return round(self.release_progress / self.release_age * 100)

    @property
    def release_overdue_percent(self) -> int:
        if self.is_release_overdue:
            return round(self.release_overdue / self.release_age * 100)
        else:
            return 0

    def ack(self, season: int | None, episode: int, revision: int = None, force: bool = False):
        if self.status == self.WatchStatus.Import:
            force = True
            self.status = self.WatchStatus.Watch

        if season is None:
            season = 0
        if revision is None:
            revision = 0

        if not force:
            if season < self.season:
                return False
            elif season == self.season and episode < self.episode:
                return False
            elif season == self.season and episode == self.episode and revision <= self.revision:
                return False

        if self.status == self.WatchStatus.Watch and episode == self.show.episodes:
            self.status = self.WatchStatus.Complete

        self.season = season
        self.episode = episode
        self.revision = revision
        self.save()

src/app/watchlist/forms.py
import re

from django import forms


class TwcliImportForm(forms.Form):
    sources = forms.FileField(required=False)
    seen = forms.FileField(required=False)


class MalinderImportForm(forms.Form):
    choice = forms.CharField(widget=forms.Textarea)
    watchlist = forms.CharField()

    def clean_choice(self):
        choice = self.cleaned_data['choice']
        result = re.findall(r"https://myanimelist.net/anime/(\d{5,})", choice, re.MULTILINE)
        return result

src/app/watchlist/templates/watchlist/base.html
{% extends "base.html" %}
{% load static %}

{% block content-wrapper %}
<div id="content-wrapper" class="container-fluid">
{% block content %}
Dummy block
{% endblock %}
</div>
{% endblock %}

{% block breadcrumbs %}
<li class="breadcrumb-item active"><a href="{% url 'index' %}">Shows</a></li>
{% endblock %}

src/app/watchlist/templates/watchlist/import_malinder_form.html
{% extends "watchlist/base.html" %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item active">Watchlists</li>
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" class="btn btn-warning" value="Import">
</form>
{% endblock %}

src/app/watchlist/templates/watchlist/import_twcli_form.html
{% extends "watchlist/base.html" %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item active">Watchlists</li>
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form }}
  <input type="submit" class="btn btn-warning" value="Import">
</form>
{% endblock %}

src/app/watchlist/templates/watchlist/watchlist_detail.html
{% extends "watchlist/base.html" %}
{% load static %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'watchlist:list' %}">Watchlists</a></li>
<li class="breadcrumb-item active">{{ object.name }}</li>
{% endblock %}

{% block content %}
<h2>Episodes</h2>
<form method="post" novalidate>
{% csrf_token %}
<input type="hidden" name="redirect" value="{% url 'watchlist:detail' object.id %}">
<table class="table">
  <tr><th>Title</th><th>File Details</th><th>Action</th></tr>
{% for wle in object.get_active_entries %}
  {% for ep in wle.get_new_episodes %}
    <tr>
      <td>{{ ep.title }}</td>
      <td>{{ ep }}</td>
      <td><input class="btn btn-info"type="submit" formaction="{% url 'watchlist:ack' object.id wle.id %}?season={{ep.season}}&episode={{ep.episode}}&revision={{ep.revision}}" value="Ack {{ ep.episode_counter }}"></td>
    </tr>
  {% endfor %}
{% endfor %}
</table>
</form>


<h2>Watch-Links</h2>
<div id="link-container">
  <div id="link-data" style="position: absolute;">
{% for link in object.get_new_watchlinks %}
    <a href="{{link.url}}">{{ link.url }}</a><br>
{% empty %}
No new watchlinks available
{% endfor %}
  </div>
  <div id="link-names" style="margin-left: 20em;">
{% for link in object.get_new_watchlinks %}
    <span>{{ link.show }} {{ link.episode }}</span><br>
{% empty %}
No new watchlinks available
{% endfor %}
  </div>
</div>


<h2>Watched Shows</h2>
<table class="table">
  <thead><tr>
    <th>Ext Reference</th>
    <th>ID</th>
    <th>Title</th>
    <th>Status</th>
    <th>Episodes</th>
    <th>Bookmark</th>
    <th>Current</th>
    <th>Cache age</th>
    <th>Release age</th>
    <th>Refresh</th>
  </tr></thead>
  <tbody>
{% for wl_entry in object.entries.all %}
  <tr>
    <td>
      {% for i, u in wl_entry.show.get_ext_uris %}<a href="{{u}}">{{i}}</a>{% endfor %}
    </td>
    <td><a href="{% url 'watchlist:entry_detail' wl_entry.id %}">{{wl_entry.id}}</a></td>
    <td>{{ wl_entry.show.name }}</td>
    <td>{{ wl_entry.get_status_display }}</td>
    <td>{{ wl_entry.show.episodes|default:'?' }}</td>
    <td>{{ wl_entry.episode_counter }}</td>
    <td>{{ wl_entry.cache_episode_counter }}</td>
    <td>{{ wl_entry.cache_refresh_date|timesince }}</td>
    <td>{% include "./incl/week_progress.html" with item=wl_entry %}</td>
    <td>
      {% if wl_entry.show.ext_srcs.all.count > 0 %}
     <a class="btn btn-warning" href="{% url 'show:refresh' wl_entry.show.id %}?redirect={% url 'watchlist:detail' object.id %}">Refresh</a>
      {% else %}
        {% if wl_entry.show.release_date <= today %}
          <a class="btn btn-success" href="{% url 'show:add_src_nyaa' wl_entry.show.id %}">Add Source ({{ wl_entry.show.release_date }})</a>
        {% else %}
          <a class="btn btn-secondary" href="{% url 'show:add_src_nyaa' wl_entry.show.id %}">Add Source ({{ wl_entry.show.release_date }}) </a>
        {% endif %}
      {% endif %}
    </td>
  </tr>
{% empty %}
  <tr><td colspan="5">No shows available</td></tr>
{% endfor %}
  </tbody>
</table>
<div>
  <a class="btn btn-dark" href="{#% url 'show:show_create' %#}">Create a new show</a>
  <a class="btn btn-dark" href="{#% url 'show:show_import_mal' %#}">Import show from MyAnimeList</a>
  <form method="post" novalidate>
    {% csrf_token %}
    <input type="hidden" name="redirect" value="{% url 'watchlist:detail' object.id %}">
    <input type="submit" class="btn btn-success" formaction="{% url 'watchlist:refresh_promising' object.id%}" value="Refresh promising">
    <input type="submit" class="btn btn-warning" formaction="{% url 'watchlist:refresh_all' object.id%}" value="Refresh all">
  </form>
</div>
{% endblock %}

src/app/watchlist/templates/watchlist/watchlist_list.html
{% extends "watchlist/base.html" %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item active">Watchlists</li>
{% endblock %}

{% block content %}
<table class="table">
  <thead><tr>
    <th>ID</th>
    <th>Name</th>
    <th>Created</th>
    <th>Entries</th>
  </tr></thead>
  <tbody>
{% for object in object_list %}
  <tr>
    <td><a href="{% url 'watchlist:detail' object.pk %}">{{object.id}}</a></td>
    <td><a href="{% url 'watchlist:detail' object.pk %}">{{object.name}}</a></td>
    <td>{{ object.created|date:"Y-m-d" }}</td>
    <td>{{ object.entries.count }}</td>
  </tr>
{% empty %}
  <tr><td colspan="5">No watchlists available</td></tr>
{% endfor %}
  </tbody>
</table>
<div>
  <a class="btn btn-primary" href="{#% url 'show:watchlist_create' %#}">Create a new watchlist</a>
  <a class="btn btn-secondary" href="{% url 'watchlist:import_twcli' %}">Import from twcli</a>
  <a class="btn btn-secondary" href="{% url 'watchlist:import_malinder' %}">Import from malinder</a>
</div>
{% endblock %}

src/app/watchlist/templates/watchlist/watchlistentry_detail.html
{% extends "watchlist/base.html" %}
{% load static %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'watchlist:list' %}">Watchlists</a></li>
<li class="breadcrumb-item"><a href="{% url 'watchlist:detail' object.watchlist.id %}">{{ object.watchlist.name }}</a></li>
<li class="breadcrumb-item active">{{ object.id }} ({{ object.show.name }})</li>
{% endblock %}

{% block content %}
<h2>WatchlistEntry Details</h2>
<table class="table">
  <tr><th>Show [{{object.show.id}}]</th><td><a href="{% url 'show:detail' object.show.id %}">{{ object.show.name }}</a></td></tr>
  <tr><th>Watchlist [{{object.watchlist.id}}]</th><td><a href="{% url 'watchlist:detail' object.watchlist.id %}">{{ object.watchlist.name }}</a></td></tr>
  <tr><th>Ext Reference</th><td>{% for i, u in object.show.get_ext_uris %}<a href="{{u}}">{{i}}</a>{% endfor %}</td></tr>
  <tr><th>Status</th><td>{{ object.get_status_display }}</td>
  <tr><th>Episodes</th><td>{{ object.show.episodes }}</td>
  <tr><th>Bookmark</th><td>{{ object.episode_counter }}</td>
  <tr><th>Current</th><td>{{ object.cache_episode_counter }}</td>
  <tr><th>Cache age</th><td>{{ object.cache_refresh_date|timesince }}</td>
  <tr><th>Release age</th><td>{{ object.cache_release_date|timesince }}</td>
  <tr>
    <th>Actions</th>
    <td>
      <a class="btn btn-primary" href="{% url 'watchlist:entry_update' object.id %}">Edit</a>
      {% if object.show.ext_srcs.all.count > 0 %}
        <a class="btn btn-warning" href="{% url 'show:refresh' object.show.id %}?redirect={% url 'watchlist:entry_detail' object.id %}">Refresh</a>
      {% else %}
        {% if object.show.release_date <= today %}
          <a class="btn btn-success" href="{% url 'show:add_src_nyaa' object.show.id %}">Add Source ({{ object.show.release_date }})</a>
        {% else %}
          <a class="btn btn-secondary" href="{% url 'show:add_src_nyaa' object.show.id %}">Add Source ({{ object.show.release_date }}) </a>
        {% endif %}
      {% endif %}
      <a class="btn btn-warning" href="{% url 'show:update' object.show.id %}?redirect={% url 'watchlist:entry_detail' object.id %}">Update</a>
    </td>
  </tr>
</table>

<h2>Episodes</h2>
<form method="post" novalidate>
{% csrf_token %}
<input type="hidden" name="redirect" value="{% url 'watchlist:entry_detail' object.id %}">
<table class="table">
  <tr><th>Title</th><th>File Details</th><th>Action</th></tr>
  {% for ep in object.get_episodes %}
    <tr>
      <td>{{ ep.title }}</td>
      <td>{{ ep }}</td>
      <td>
        {% if ep.revision is None and object.season == ep.season and object.episode == ep.episode or object.revision == ep.revision and object.season == ep.season and object.episode == ep.episode %}
        <span class="btn btn-dark">Bookmark</span>
        {% else %}
        <input class="btn btn-info"type="submit" formaction="{% url 'watchlist:ack' object.watchlist.id object.id %}?season={{ep.season}}&episode={{ep.episode}}&revision={{ep.revision}}" value="Ack {{ ep.episode_counter }}">
        {% endif %}
      </td>
    </tr>
{% empty %}
    <tr><td colspan="3">No episodes available</td></tr>
{% endfor %}
</table>
</form>


<h2>Watch-Links</h2>
{% for link in object.get_watchlinks %}
<a href="{{link}}">{{ link }}</a><br>
{% empty %}
No new watchlinks available
{% endfor %}
{% endblock %}

src/app/watchlist/templates/watchlist/watchlistentry_form.html
{% extends "watchlist/base.html" %}
{% load static %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'watchlist:list' %}">Watchlists</a></li>
<li class="breadcrumb-item"><a href="{% url 'watchlist:detail' object.watchlist.id %}">{{ object.watchlist.name }}</a></li>
<li class="breadcrumb-item active">{{ object.id }} ({{ object.show.name }})</li>
{% endblock %}

{% block content %}
<h2>Edit WatchlistEntry</h2>
<form method="post">
  {% csrf_token %}
  <table class="table">
    <tr><th>Show [{{object.show.id}}]</th><td><a href="{% url 'show:detail' object.show.id %}">{{ object.show.name }}</a></td></tr>
    <tr><th>Watchlist</th><td>{{ form.watchlist }}</td></tr>
    <tr><th>Status</th><td>{{ form.status }}</td></tr>
    <tr><th>Episodes</th><td>{{ object.show.episodes }}</td></tr>
    <tr><th>Ext Reference</th><td>{% for i, u in object.show.get_ext_uris %}<a href="{{u}}">{{i}}</a>{% endfor %}</td></tr>
    <tr><th>Bookmark</th><td>{{ object.episode_counter }}</td>
    <tr><th>Current</th><td>{{ object.cache_episode_counter }}</td>
    <tr><th>Cache age</th><td>{{ object.cache_refresh_date|timesince }}</td>
    <tr><th>Release age</th><td>{{ object.cache_release_date|timesince }}</td>
  </table>
  <input type="submit" class="btn btn-warning" value="Save">
</form>
{% endblock %}