archive/app/shows/urls.py
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views

app_name = "shows"

router = routers.DefaultRouter()
router.register("show", api.ShowViewSet)
router.register("episode", api.EpisodeViewSet)

urlpatterns = (
    path("api/v1/", include(router.urls)),

    path("show/", views.ShowListView.as_view(), name="show_list"),
    path("show/create", views.ShowCreateView.as_view(), name="show_create"),
    path("show/import", views.ShowImportMalView.as_view(), name="show_import_mal"),
    path("show/<int:pk>", views.ShowDetailView.as_view(), name="show_detail"),
    path("show/<int:pk>/update", views.ShowUpdateView.as_view(), name="show_update"),
    path("show/<int:pk>/watch", views.ShowWatchView.as_view(), name="show_watch"),

    path("episode/", views.EpisodeListView.as_view(), name="episode_list"),
    path("episode/create/", views.EpisodeCreateView.as_view(), name="episode_create"),
    path("episode/<int:pk>", views.EpisodeDetailView.as_view(), name="episode_detail"),
    path("episode/<int:pk>/update", views.EpisodeUpdateView.as_view(), name="episode_update"),
)

archive/app/shows/models.py
from django.db import models
from django.urls import reverse
from .helper import nyaa


class SOURCES(models.TextChoices):
    NONE = 'NONE', 'none'
    NYAA = 'NYAA', 'nyaa'


class Show(models.Model):
    # Fields
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    name_en = models.CharField(max_length=255, null=True, blank=True)
    name_jp = models.CharField(max_length=255, null=True, blank=True)
    name_jp_romaji = models.CharField(max_length=255, null=True, blank=True)
    comment = models.CharField(max_length=255, null=True, blank=True)
    mal_id = models.PositiveIntegerField(null=True, blank=True, unique=True)
    release_date = models.DateField(null=True, blank=True)
    source_type = models.CharField(max_length=16, choices=SOURCES.choices, default=SOURCES.NONE)
    source = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        pass

    def __str__(self):
        return str(self.name_en)

    def get_absolute_url(self):
        return reverse("show:show_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("show:show_update", args=(self.pk,))

    def get_sources(self) -> list:
        if self.source_type == SOURCES.NYAA:
            if self.source is not None and self.source != "":
                print(f"Fetching source {self.source_type}:{self.source}")
        data = nyaa.get_feed(str(self.source))
        return data


class Episode(models.Model):
    # Relationships
    show = models.ForeignKey(Show, on_delete=models.PROTECT)

    # Fields
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    num = models.PositiveIntegerField()
    title = models.CharField(max_length=128, blank=True, null=True)
    pubdate = models.DateField(blank=True, null=True)

    class Meta:
        pass

    def __str__(self):
        if self.title is not None:
            return f"{self.num:02} - {self.title}"
        else:
            return f"{self.num:02}"

    def get_absolute_url(self):
        return reverse("show:episode_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("show:episode_update", args=(self.pk,))

archive/app/shows/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.core import exceptions as django_exceptions

from .helper import mal
from . import models

BUTTON_SUBMIT_NAME = 'submit'
BUTTON_QUERY_NAME = 'query'

MAL_IMPORT_FIELDS = ['id', 'title', 'alternative_titles', 'start_date', 'end_date', 'media_type', 'status',
                     'num_episodes', 'start_season']
SEASON_MONTH_LOOKUP = {
    'winter': 1,
    'spring': 4,
    'summer': 7,
    'fall': 10,
}


class ShowForm(forms.ModelForm):
    class Meta:
        model = models.Show
        fields = [
            "name_en",
            "name_jp_romaji",
            "name_jp",
            "comment",
            "release_date",
            "source_type",
            "source",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.add_input(Submit('submit', 'Save'))


class ShowImportForm(forms.ModelForm):
    # additional fields in form, not to be saved
    ack = forms.BooleanField(required=False)
    raw = forms.CharField(required=False, widget=forms.Textarea)

    class Meta:
        model = models.Show
        fields = [
            "mal_id",
            "name_en",
            "name_jp_romaji",
            "name_jp",
            "comment",
            "release_date",
            "source_type",
            "source",
            "ack",
        ]

    def __init__(self, *args, **kwargs):
        # super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.add_input(Submit(BUTTON_SUBMIT_NAME, 'Save'))
        self.helper.add_input(Submit(BUTTON_QUERY_NAME, 'Query MAL'))

        # If the form has been submitted, populate the disabled field
        if 'data' in kwargs and BUTTON_QUERY_NAME in kwargs['data']:
            data = kwargs['data'].copy()
            self.prefix = kwargs.get('prefix')
            mal_id = data['mal_id']
            anime = mal.get_anime(mal_id, MAL_IMPORT_FIELDS)
            data[self.add_prefix('raw')] = str(anime)

            if 'alternative_titles' not in anime:
                # if there are no specific names, use title as english name
                data[self.add_prefix('name_en')] = anime['title']
            else:
                if 'en' in anime['alternative_titles']:
                    # if there's a specific english name, store title in comment
                    data[self.add_prefix('name_en')] = anime['alternative_titles']['en']
                    data[self.add_prefix('name_jp_romaji')] = anime['title']
                else:
                    # otherwise assume main name is english for now
                    data[self.add_prefix('name_en')] = anime['title']
                if 'ja' in anime['alternative_titles']:
                    # store japanese name if available
                    data[self.add_prefix('name_jp')] = anime['alternative_titles']['ja']
                    if 'en' not in anime['alternative_titles']:
                        # if there is no specific english name, assume title is english
                        data[self.add_prefix('name_en')] = anime['title']
            if 'start_date' in anime:
                data[self.add_prefix('release_date')] = anime['start_date']
            elif 'start_season' in anime:
                month = SEASON_MONTH_LOOKUP[anime['start_season']['season']]
                year = anime['start_season']['year']
                data[self.add_prefix('release_date')] = f"{year}-{month}-01"
            kwargs['data'] = data
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        if 'submit' in self.data:
            if not cleaned_data['ack']:
                self.add_error('ack', "Check 'acknowledge' to save")
        elif 'query' in self.data:
            if 'mal_id' not in cleaned_data or cleaned_data['mal_id'] is None or cleaned_data['mal_id'] == '':
                self.add_error('mal_id', "Enter a MAL ID for lookup")
            raise django_exceptions.ValidationError("Running import, not saving yet. Please check/correct and save!")


class EpisodeForm(forms.ModelForm):
    class Meta:
        model = models.Episode
        fields = [
            "num",
            "title",
            "pubdate",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.add_input(Submit('submit', 'Save'))

archive/app/shows/views.py
from django.views import generic

from . import forms
from . import models
from .helper import nyaa


class ShowListView(generic.ListView):
    model = models.Show


class ShowCreateView(generic.CreateView):
    model = models.Show
    form_class = forms.ShowForm


class ShowImportMalView(generic.CreateView):
    model = models.Show
    form_class = forms.ShowImportForm


class ShowDetailView(generic.DetailView):
    model = models.Show


class ShowWatchView(generic.DetailView):
    model = models.Show

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object.source_type == models.SOURCES.NYAA:
            if self.object.source is not None and self.object.source != "":
                print(f"Fetching source {self.object.source_type}:{self.object.source}")
                # context['sources'] = nyaa.get_feed(self.object.source)
                context['sources'] = self.object.get_sources()
        return context


class ShowUpdateView(generic.UpdateView):
    model = models.Show
    form_class = forms.ShowForm


class EpisodeListView(generic.ListView):
    model = models.Episode


class EpisodeCreateView(generic.CreateView):
    model = models.Episode
    form_class = forms.EpisodeForm


class EpisodeDetailView(generic.DetailView):
    model = models.Episode


class EpisodeUpdateView(generic.UpdateView):
    model = models.Episode

archive/app/shows/templates/shows/base.html
{% extends "base.html" %}
{% load static %}

{% block content-wrapper %}
<div id="content-wrapper" class="container-fluid">
{% block content %}
Dummy block
{% endblock %}
</div>
{% endblock %}

{% block breadcrumbs %}
<li class="breadcrumb-item active"><a href="{% url 'index' %}">Shows</a></li>
{% endblock %}

archive/app/shows/templates/shows/episode_detail.html
{% extends "shows/base.html" %}
{% load static %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'show:episode_list' %}">Episodes</a></li>
<li class="breadcrumb-item active">{{ object.pk }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tr><td>show</td><td>{{ object.seen }}</td></tr>
    <tr><td>reference</td><td>{{ object.acquired }}</td></tr>
    <tr><td>season</td><td>{{ object.season }}</td></tr>
    <tr><td>num</td><td>{{ object.num }}</td></tr>
    <tr><td>title</td><td>{{ object.title }}</td></tr>
    <tr><td>pubdate</td><td>{{ object.pubdate }}</td></tr>
    <tr><td>runtime</td><td>{{ object.runtime }}</td></tr>
    <tr><td>created</td><td>{{ object.created }}</td></tr>
    <tr><td>last_updated</td><td>{{ object.last_updated }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit</a>

{% endblock %}

archive/app/shows/templates/shows/episode_form.html
{% extends "shows/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'show:episode_list' %}">Episodes</a></li>
{% if object %}
<li class="breadcrumb-item active"><a href="{% url 'show:episode_detail' object.pk %}">{{ object.pk }}</a></li>
<li class="breadcrumb-item">Update</li>
{% else %}
<li class="breadcrumb-item">Create</li>
{% endif %}
{% endblock %}

{% block content %}
{% crispy form %}
{% endblock %}

archive/app/shows/templates/shows/episode_list.html
{% extends "shows/base.html" %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item active">Episodes</li>
{% endblock %}


{% block content %}
{% for object in object_list %}
  <div class="m-2"><a href="{{object.get_absolute_url}}">{{object}}</a></div>
{% endfor %}
<div><a class="btn btn-primary" href="{% url 'show:episode_create' %}">Create a new episode</a></div>
{% endblock %}

archive/app/shows/templates/shows/show_detail.html
{% extends "shows/base.html" %}
{% load static %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'show:show_list' %}">Shows</a></li>
<li class="breadcrumb-item active">{{ object.pk }}</li>
{% endblock %}

{% block content %}
<h2>Details</h2>
<table class="table">
    <tr><td>created</td><td>{{ object.created }}</td></tr>
    <tr><td>last_updated</td><td>{{ object.last_updated }}</td></tr>
    <tr><td>name_en</td><td>{{ object.name_en }}</td></tr>
    <tr><td>name_jp_romaji</td><td>{{ object.name_jp_romaji }}</td></tr>
    <tr><td>name_jp</td><td>{{ object.name_jp }}</td></tr>
    <tr><td>comment</td><td>{{ object.comment }}</td></tr>
    <tr><td>MyAnimeList</td>
        <td>
            {% if object.mal_id != None %}
            <a href="https://myanimelist.net/anime/{{object.mal_id}}">{{object.mal_id}}</a>
            {% endif %}
        </td>
    </tr>
    <tr><td>Release Date</td><td>{{ object.release_date }}</td></tr>
    <tr><td>Source</td><td>{{ object.source_type }}: {{ object.source }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit</a>
{% if not sources and object.source_type != 'NONE' %}
<a class="btn btn-secondary" href="{% url 'show:show_watch' object.pk %}">Watch {{object.source_type}}</a>
{% endif %}

{% if sources %}
<h2>Sources [{{object.source_type }}]</h2>
<table>
  <thead><tr>
    <th>Season</th>
    <th>Episode</th>
    <th>Episode title</th>
    <th>Size</th>
    <th>link</th>
  </tr></thead>
  <tbody>
{% for ep in sources %}
  <tr>
    <td>{{ ep.season }}</td>
    <td>{{ ep.episode }}</td>
    <td>{{ ep.title }}</td>
    <td>{{ ep.size }}</td>
    <td><a href="{{ep.dl}}">Watch</a></td>
  </tr>
{% empty %}
  <tr><td colspan="3">No sources available</td></tr>
{% endfor %}
  </tbody>
</table>
{#{sources}#}
{% endif %}
{% endblock %}

archive/app/shows/templates/shows/show_form.html
{% extends "shows/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'show:show_list' %}">Shows</a></li>
{% if object %}
<li class="breadcrumb-item active"><a href="{% url 'show:show_detail' object.pk %}">{{ object.pk }}</a></li>
<li class="breadcrumb-item">Update</li>
{% else %}
<li class="breadcrumb-item">Create</li>
{% endif %}
{% endblock %}

{% block content %}
{% crispy form %}
{% endblock %}

archive/app/shows/templates/shows/show_list.html
{% extends "shows/base.html" %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item active">Shows</li>
{% endblock %}

{% block content %}
<table>
  <thead><tr>
    <th>MyAnimeList</th>
    <th>Title EN</th>
    <th>Title JP</th>
    <th>Title Romaji</th>
    <th>Date</th>
  </tr></thead>
  <tbody>
{% for object in object_list %}
  <tr>
    <td>
      {% if object.mal_id is not None %}
      <a href="https://myanimelist.net/anime/{{object.mal_id}}">{{object.mal_id}}</a>
      {% endif %}
    </td>
    <td>
      {% if object.name_en is not None %}
      <a href="{% url 'show:show_detail' object.pk %}">{{object.name_en|default:"-"}}</a>
      {% else %}
      -
      {% endif %}
    </td>
    <td>
      {% if object.name_jp_romaji is not None %}
      <a href="{% url 'show:show_detail' object.pk %}">{{object.name_jp_romaji|default:"-"}}</a>
      {% else %}
      -
      {% endif %}
    </td>
    <td>
      {% if object.name_jp is not None %}
      <a href="{% url 'show:show_detail' object.pk %}">{{object.name_jp|default:"-"}}</a>
      {% else %}
      -
      {% endif %}
    </td>
    <td>
      {% if object.release_date is not None %}
      {{object.release_date}}
      {% else %}
      -
      {% endif %}
    </td>
  </tr>
{% empty %}
  <tr><td colspan="5">No shows available</td></tr>
{% endfor %}
  </tbody>
</table>
<div>
  <a class="btn btn-primary" href="{% url 'show:show_create' %}">Create a new show</a>
  <a class="btn btn-secondary" href="{% url 'show:show_import_mal' %}">Import show from MyAnimeList</a>
</div>
{% endblock %}