src/app/show/urls.py
from django.urls import path, include

from . import views

app_name = "show"

urlpatterns = (
    path("", views.ShowListView.as_view(), name="list"),
    path("<int:pk>", views.ShowDetailView.as_view(), name="detail"),
    path("<int:pk>/watch", views.ShowWatchView.as_view(), name="watch"),
    path("<int:pk>/refresh", views.refresh_show_cache, name="refresh"),
    path("<int:pk>/update", views.update_show, name="update"),
    path("<int:sid>/add/src/nyaa", views.AddNyaaSourceView.as_view(), name="add_src_nyaa"),
)

src/app/show/models.py
import urllib.parse
from datetime import timedelta

import django.core.exceptions
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.utils.http import urlencode

from .helper import mal_nomodel as mal_helper_nomodel
from .helper import nyaa as nyaa_helper


class Show(models.Model):
    # Fields
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)

    name = models.CharField(max_length=255)
    name_native = models.CharField(max_length=255, null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    broadcast_day = models.PositiveIntegerField(blank=True, null=True)
    broadcast_time = models.TimeField(null=True, blank=True)
    episodes = models.PositiveIntegerField(blank=True, null=True)

    # ext_id: reverse foreign key -> ExternalId
    # ext_source: reverse foreign key -> ExternalSource

    class Meta:
        pass

    def __str__(self):
        return str(self.name)

    def get_ext_uris(self):
        return [(ref.twid, ref.uri) for ref in self.ext_ids.all()]

    def get_source_uris(self):
        return [(ref.twid, ref.uri) for ref in self.ext_srcs.all()]

    def update_showdata(self):
        refs = self.ext_ids.all()
        for ref in refs:
            ref.update_showdata()

    def get_cachedata(self, season=None, episode=None, revision=None) -> list[django.db.models.QuerySet]:
        sources = self.ext_srcs.all()
        cache = []
        for src in sources:
            for cache_item in src.get_cachedata(season, episode, revision):
                cache.append(cache_item)
        return cache

    @staticmethod
    def _update_cache(sources: models.QuerySet):
        for src in sources:
            src.fetch_source_data()

    def update_cache_force(self):
        sources = self.ext_srcs.all()
        return self._update_cache(sources)

    def update_cache_promising(self):
        cache_cutoff = timezone.now() - timedelta(minutes=10)
        release_cutoff = timezone.now() - timedelta(days=6)
        sources = self.ext_srcs.filter((Q(cached_at__isnull=True) | Q(cached_at__lt=cache_cutoff)) &
                                       (Q(latest_release_date__isnull=True) | Q(latest_release_date__lt=release_cutoff))
                                       )
        return self._update_cache(sources)


class ExternalId(models.Model):
    PROVIDER_SLUG = "DUMMY"
    DB_RELATEDNAME = f'ext_ids_{PROVIDER_SLUG.lower()}' if PROVIDER_SLUG != "DUMMY" else 'ext_ids'
    DB_RELATEDQUERYNAME = f'ext_id_{PROVIDER_SLUG.lower()}' if PROVIDER_SLUG != "DUMMY" else 'ext_id'

    show = models.ForeignKey(Show, null=True, blank=True, on_delete=models.SET_NULL,
                             related_name=DB_RELATEDNAME, related_query_name=DB_RELATEDQUERYNAME)

    @property
    def extid(self) -> str:
        return "NA"

    @property
    def extid_opt(self) -> str | None:
        return None

    @property
    def twid(self) -> str:
        if self.extid_opt:
            return f'{self.PROVIDER_SLUG}[{self.extid_opt}]:{self.extid}'
        else:
            return f'{self.PROVIDER_SLUG}:{self.extid}'

    @property
    def uri(self):
        return "http://domain.invalid/NA"

    def __str__(self):
        return self.twid

    def update_showdata(self):
        raise NotImplemented

    class Meta:
        abstract = True


class MalId(ExternalId):
    class MalType(models.TextChoices):
        Anime = 'A', 'Anime'
        Manga = 'M', 'Manga'

    PROVIDER_SLUG = "MAL"
    PROVIDER_BASEURL = "https://myanimelist.net"
    PROVIDER_TYPEPATH = {
        MalType.Anime: '/anime',
        MalType.Manga: '/manga',
    }

    mal_type = models.CharField(max_length=1, choices=MalType.choices, default=MalType.Anime)
    mal_id = models.PositiveIntegerField(unique=True)

    @property
    def extid(self):
        return self.mal_id

    @property
    def extid_opt(self):
        return self.mal_type

    @property
    def uri(self):
        return f'{self.PROVIDER_BASEURL}{self.PROVIDER_TYPEPATH[self.MalType(self.mal_type)]}/{self.mal_id}'

    def update_showdata(self):
        s = self.show
        s.episodes = mal_helper_nomodel.get_show_episodes(self.mal_id)
        s.save()


class ExternalSource(models.Model):
    SOURCE_SLUG = "DUMMY"
    DB_RELATEDNAME = f'ext_srcs_{SOURCE_SLUG.lower()}' if SOURCE_SLUG != "DUMMY" else 'ext_srcs'
    DB_RELATEDQUERYNAME = f'ext_src_{SOURCE_SLUG.lower()}' if SOURCE_SLUG != "DUMMY" else 'ext_src'

    show = models.ForeignKey(Show, null=True, blank=True, on_delete=models.SET_NULL,
                             related_name=DB_RELATEDNAME, related_query_name=DB_RELATEDQUERYNAME)
    cached_at = models.DateTimeField(blank=True, null=True)
    latest_release_date = models.DateTimeField(blank=True, null=True)

    @property
    def twid(self) -> str:
        return f'{self.SOURCE_SLUG}:{self.id}'

    @property
    def uri(self):
        return "http://domain.invalid/NA"

    def fetch_source_data(self, update_cache: bool = True) -> list:
        raise NotImplemented

    def get_cachedata(self, season=None, episode=None, revision=None) -> django.db.models.QuerySet:
        raise NotImplemented

    def __str__(self):
        return f'{self.SOURCE_SLUG}'

    class Meta:
        abstract = True


class NyaaSource(ExternalSource):
    SOURCE_SLUG = 'NYAA'
    SOURCE_BASEURL = 'https://nyaa.si/'
    # SOURCE_DEFAULTPARAMS = {'page': 'rss', 'c': '0_0', 'f': 0}
    SOURCE_DEFAULTPARAMS = {}
    term = models.CharField(max_length=255)
    user = models.CharField(max_length=255, null=True, blank=True)

    @property
    def uri(self):
        return self.get_uri()

    def get_uri(self, params: dict = {}):
        return NyaaSource.build_uri(str(self.term), str(self.user), **params)

    @staticmethod
    def build_uri(term: str, user: str = None, **kwargs):
        query = NyaaSource.SOURCE_DEFAULTPARAMS.copy()
        query['q'] = str(term)
        if user is not None:
            query['u'] = str(user)
        for kw in kwargs:
            query[kw] = kwargs[kw]
        urlparams = urlencode(query)
        return f'{NyaaSource.SOURCE_BASEURL}?{urlparams}'

    def __str__(self):
        if self.user:
            return f'{self.SOURCE_SLUG}[{self.user}]:{urllib.parse.quote_plus(str(self.term))}'
        else:
            return f'{self.SOURCE_SLUG}:{urllib.parse.quote_plus(str(self.term))}'

    def get_cachedata(self, season=None, episode=None, revision=None) -> django.db.models.QuerySet:
        cache = self.cache_items.all()
        if season is not None:
            cache = cache.exclude(season__lt=season)
            if episode is not None and episode > 0:
                if revision is None or revision == 0:
                    cache = cache.exclude(season=season, episode__lte=episode)
                else:
                    cache = cache.exclude(season=season, episode__lt=episode)
                    cache = cache.exclude(season=season, episode=episode, revision__lte=revision)
        return cache.order_by('-season', '-episode', '-revision')

    def fetch_source_data(self, update_cache: bool = True) -> list:
        uri = self.get_uri({'page': 'rss'})
        data = nyaa_helper.get_feed(uri)
        if update_cache:
            self._update_cache(data)
        return data

    def _update_cache(self, data: list[dict]) -> None:
        # data: list(dict(title, size, dl, season, episode, increment, guid, pub_date))
        if self.cached_at is not None and self.cached_at > (timezone.now() - timedelta(minutes=5)):
            raise django.core.exceptions.BadRequest("Rate limit exceeded")
        self.cache_items.update(outdated=True)  # First mark all db objects outdated
        for item in data:
            try:
                dflts = {
                    # "show": self.show,
                    "title": item['title'],
                    "url": item['dl'],
                    "episode": item['episode'],
                    "pub_date": item['pub_date'],
                    "season": item['season'] if 'season' in item else 0,
                }
            except KeyError:
                continue

            obj, created = self.cache_items.get_or_create(guid=item['guid'], defaults=dflts)
            if created:
                if 'increment' in item:
                    obj.increment = item['increment']
            obj.outdated = False  # mark refreshed objects as non-outdated, so those missing in rss remain marked
            obj.save()
            if self.latest_release_date is None or item['pub_date'] > self.latest_release_date:
                self.latest_release_date = item['pub_date']
        self.cached_at = timezone.now()
        self.save()


class CacheItem(models.Model):
    source = models.ForeignKey(ExternalSource, on_delete=models.CASCADE,
                               related_name="cache_items", related_query_name="cache_item")
    timestamp = models.DateTimeField(auto_now=True, editable=False)
    outdated = models.BooleanField(default=False)

    # def __str__(self):
    #     return f'{self.SOURCE_SLUG}'

    class Meta:
        abstract = True


class NyaaCacheItem(CacheItem):
    source = models.ForeignKey(NyaaSource, on_delete=models.CASCADE,
                               related_name="cache_items", related_query_name="cache_item")
    guid = models.CharField(max_length=255, unique=True)
    pub_date = models.DateTimeField()
    season = models.PositiveIntegerField(blank=True, null=True)
    episode = models.PositiveIntegerField()
    revision = models.PositiveIntegerField(blank=True, null=True)
    title = models.CharField(max_length=255)
    url = models.URLField(unique=True)

    def __str__(self):
        return f'[{self.timestamp}] {self.source.show} {self.episode_counter}'

    @property
    def episode_counter(self):
        if self.season <= 1:
            out = f'{self.episode}'

src/app/show/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from . import models
from .helper import nyaa as nyaa_helper


class ShowListView(LoginRequiredMixin, generic.ListView):
    model = models.Show


class ShowDetailView(LoginRequiredMixin, generic.DetailView):
    model = models.Show

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for s in self.object.ext_srcs.all():
            context['source_cache'] = s.cache_items.filter(outdated=False)
        return context


class ShowWatchView(ShowDetailView):
    # inherits LoginRequiredMixin
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for s in self.object.ext_srcs.all():
            context['sources'] = s.fetch_source_data()
        return context


@login_required
def refresh_show_cache(request, pk: int):
    obj = models.Show.objects.get(id=pk)
    obj.update_cache_force()
    if 'redirect' in request.POST:
        return HttpResponseRedirect(request.POST['redirect'])
    elif 'redirect' in request.GET:
        return HttpResponseRedirect(request.GET['redirect'])
    else:
        return HttpResponseRedirect(reverse('show:detail', args=(obj.id,)))


@login_required
def update_show(request, pk: int):
    obj = models.Show.objects.get(id=pk)
    obj.update_showdata()
    if 'redirect' in request.POST:
        return HttpResponseRedirect(request.POST['redirect'])
    elif 'redirect' in request.GET:
        return HttpResponseRedirect(request.GET['redirect'])
    else:
        return HttpResponseRedirect(reverse('show:detail', args=(obj.id,)))


class AddNyaaSourceView(LoginRequiredMixin, generic.CreateView):
    model = models.NyaaSource
    fields = ('user', 'term')

    def form_valid(self, form):
        if 'create' in self.request.POST:
            self.object = form.save(commit=False)
            self.object.show = models.Show.objects.get(id=self.kwargs['sid'])
            self.object.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse('show:detail', args=(self.object.show.id,))

    def get_initial(self):
        initials = {}
        s = models.Show.objects.get(id=self.kwargs['sid'])
        if 'user' in self.request.GET:
            initials['user'] = self.request.GET['user']

        if 'term' in self.request.GET:
            initials['term'] = self.request.GET['term']
        else:
            initials['term'] = s.name

        return initials

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['show'] = models.Show.objects.get(id=self.kwargs['sid'])
        context['today'] = timezone.now()
        params = {
            'page': 'rss',
            'f': '0',  # no filter
            'c': '1_2',  # anime, english translated
        }
        if 'form' in kwargs and 'user' in kwargs['form'].cleaned_data:
            params['user'] = kwargs['form'].cleaned_data['user']
            uri = models.NyaaSource.build_uri(kwargs['form'].cleaned_data['term'], **params)
            context['source_uri'] = uri
            rss = nyaa_helper.get_feed(uri)
            context['source_data'] = [{'date': x['pub_date'], 'title': x['title'], 'size': x['size']} for x in rss]
        return context

src/app/show/templates/show/base.html
{% extends "base.html" %}
{% load static %}

{% block content-wrapper %}
<div id="content-wrapper" class="container-fluid">
{% block content %}
Dummy block
{% endblock %}
</div>
{% endblock %}

{% block breadcrumbs %}
<li class="breadcrumb-item active"><a href="{% url 'index' %}">Shows</a></li>
{% endblock %}

src/app/show/templates/show/nyaasource_form.html
{% extends "watchlist/base.html" %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'show:list' %}">Shows</a></li>
<li class="breadcrumb-item"><a href="{% url 'show:detail' show.id %}">{{ show.id }}</a></li>
<li class="breadcrumb-item active">Add Nyaa Source</li>
{% endblock %}

{% block content %}
<h1>Add Nyaa Source</h1>
<table>
  <tr><th>ID</th><td>{{ show.id }}</td></tr>
  <tr><th>Name</th><td>{{ show.name }}</td></tr>
  {% if show.name_native %}<tr><th>Native Name</th><td>{{ show.name_native }}</td></tr>{% endif %}
</table>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" class="btn btn-warning" name="test" value="Test">
  <input type="submit" class="btn btn-warning" name="create" value="Create">
</form>
{% if source_uri %}Trying <a href="{{ source_uri }}">Nyaa RSS</a>...
{% if not source_data %}
did not yield any episodes</p>
{% else %}Found {{ source_data|length }} episodes:</p>
<table>
  <thead>
  <tr><th>Date</th><th>Title</th><th>Size</th></tr>
  </thead>
  <tbody>
  {% for line in source_data %}
  <tr>
    <td>{{ line.date }}</td>
    <td>{{ line.title }}</td>
    <td>{{ line.size }}</td>
  </tr>
  {% empty %}
  <tr><td colspan="3">No Episodes found</td></tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}
{% endif %}
{% endblock %}

src/app/show/templates/show/show_detail.html
{% extends "show/base.html" %}
{% load static %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'show:list' %}">Shows</a></li>
<li class="breadcrumb-item active">{{ object.pk }}</li>
{% endblock %}

{% block content %}
<h2>Details</h2>
<table class="table">
    <tr><td>created</td><td>{{ object.created }}</td></tr>
    <tr><td>last_updated</td><td>{{ object.last_updated }}</td></tr>
    <tr><td>name</td><td>{{ object.name }}</td></tr>
    <tr><td>name_native</td><td>{{ object.name_native|default:"" }}</td></tr>
    <tr><td>Release Date</td><td>{{ object.release_date|default:"" }}</td></tr>
    <tr><td>External references</td>
        <td>{% for i, u in object.get_ext_uris %}<a href="{{u}}">{{i}}</a> {% endfor %}</td>
    </tr>
    <tr><td>Sources</td>
        <td>{% for i, u in object.get_source_uris %}<a href="{{u}}">{{i}}</a> {% endfor %}</td>
    </tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit</a>
<a class="btn btn-secondary" href="{% url 'show:watch' object.pk %}">Refresh</a>


{% if sources %}
<h2>Current Sources [{{sources.SOURCE_SLUG }}]</h2>
<table>
  <thead><tr>
    <th>Season</th>
    <th>Episode</th>
    <th>Episode title</th>
    <th>Size</th>
    <th>link</th>
  </tr></thead>
  <tbody>
{% for ep in sources %}
  <tr>
    <td>{{ ep.season }}</td>
    <td>{{ ep.episode }}</td>
    <td>{{ ep.title }}</td>
    <td>{{ ep.size }}</td>
    <td><a href="{{ep.dl}}">Watch</a></td>
  </tr>
{% empty %}
  <tr><td colspan="3">No sources available</td></tr>
{% endfor %}
  </tbody>
</table>
{% endif %}

{% if source_cache %}
<h2>Cached Source</h2>
<table>
  <thead><tr>
    <th>Season</th>
    <th>Episode</th>
    <th>Revision</th>
    <th>Publication Date</th>
    <th>Episode title</th>
    <th>Source</th>
    <th>link</th>
    <th>Cache Date</th>
  </tr></thead>
  <tbody>
{% for ep in source_cache %}
  <tr>
    <td>{{ ep.season|default:"" }}</td>
    <td>{{ ep.episode }}</td>
    <td>{{ ep.revision|default:"" }}</td>
    <td>{{ ep.pub_date }}</td>
    <td>{{ ep.title }}</td>
    <td><a href="{{ep.guid}}">Details</a></td>
    <td><a href="{{ep.url}}">Watch</a></td>
    <td>{{ ep.timestamp }}</td>
  </tr>
{% empty %}
  <tr><td colspan="3">No cached items available</td></tr>
{% endfor %}
  </tbody>
</table>
{% endif %}

{% endblock %}

src/app/show/templates/show/show_list.html
{% extends "show/base.html" %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item active">Shows</li>
{% endblock %}

{% block content %}
<table>
  <thead><tr>
    <th>ID</th>
    <th>Ext Reference</th>
    <th>Title</th>
    <th>Title (Ori)</th>
    <th>Date</th>
  </tr></thead>
  <tbody>
{% for object in object_list %}
  <tr>
    <td><a href="{% url 'show:detail' object.pk %}">{{object.id}}</a></td>
    <td>
      {% for i, u in object.get_ext_uris %}<a href="{{u}}">{{i}}</a>{% endfor %}
    </td>
    <td>{{object.name}}</td>
    <td>{{object.name_native|default:"-"}}</td>
    <td>{{object.release_date|default:"-"}}</td>
  </tr>
{% empty %}
  <tr><td colspan="5">No shows available</td></tr>
{% endfor %}
  </tbody>
</table>
<div>
  <a class="btn btn-primary" href="{#% url 'show:show_create' %#}">Create a new show</a>
  <a class="btn btn-secondary" href="{#% url 'show:show_import_mal' %#}">Import show from MyAnimeList</a>
</div>
{% endblock %}